### PR TITLE
Support constants instead of extractors

### PR DESCRIPTION
**Pull request by kibertoad**
Considering that in many cases we know which entity and which operation is the endpoint handling, passing whole function can be redundant.

### CODE REVIEW

**Review by simoneb — APPROVED** [review]
LGTM

**Comment by kibertoad** [comment]
@simoneb Thank you! Any chance you could release a new version?

**Comment by simoneb** [comment]
1.2.0 is out

**Comment by kibertoad** [comment]
@simoneb Yay! Thanks.

**Pull request merged**
